### ISSUE TITLE
Organization Support?

### ISSUE THREAD

**Issue by Caaz** [Hs1r1us/Release-AIO#1]
I could be wrong on this, but it appears this automated release doesn't work properly with an organization's repository. Getting this error when attempting to use it.
```
/home/runner/work/_actions/Hs1r1us/Release-AIO/v1.0/dist/index.js:[14](https://github.com/Caaz/rimworld-typhon/runs/8296066693?check_suite_focus=true#step:6:15)056
    owner = getRepo.match(/^[\s\w]+(?=\/)/g)[0],
                                            ^

TypeError: Cannot read property '0' of null
    at Object.719 (/home/runner/work/_actions/Hs1r1us/Release-AIO/v1.0/dist/index.js:14056:45)
    at __nccwpck_require__ (/home/runner/work/_actions/Hs1r1us/Release-AIO/v1.0/dist/index.js:14424:43)
    at /home/runner/work/_actions/Hs1r1us/Release-AIO/v1.0/dist/index.js:14441:18
    at Object.<anonymous> (/home/runner/work/_actions/Hs1r1us/Release-AIO/v1.0/dist/index.js:14442:12)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:[17](https://github.com/Caaz/rimworld-typhon/runs/8296066693?check_suite_focus=true#step:6:18):47
```
I can confirm that the action itself works on my personal projects, I'm using a nearly identical workflow in another project.

Seems that's caused by [this line](https://github.com/Hs1r1us/Release-AIO/blob/main/src/main.js#L27). Judging by the code, and the fact that I didn't define the `repo` field, it's likely pulling this from the [context.repo](https://github.com/Hs1r1us/Release-AIO/blob/main/src/main.js#L20) field here.

**Comment by Hs1r1us** [comment]
Thanks for feeeback.
Sorry, this is my mistake, the organization (or repository) name is wrongly handled when it contains special characters.
I will fix it.
